-- +goose Up
ALTER TABLE users
    ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- +goose Down
ALTER TABLE users
    DROP COLUMN created_at,
    DROP COLUMN updated_at;
